### ISSUE TITLE
Multiple line strings are indented incorrectly

### ISSUE THREAD

**Issue by benpjohnson** [2072/PHP-Indenting-for-VIm#22]
Where a file contains multiple line strings the contents of the strings are currently indented.

What should happen (I think) is to treat them the same way as heredoc. e.g. this example preserves the indenting when the quotes are replaced with heredoc.

``` php
<?php

<?php

$string = "
        a multiple
    line string
with
    different
indents
";

```

becomes:

``` php
$string = "
a multiple
line string
with
different
indents
";

```

**Comment by marlun** [comment]
I can't figure out how multi-line strings are supposed to be formatted. If I write

    $sql = "

and hit enter, shouldn't the cursor end up like

    $sql = "
        |

I've got a snippet so that I can write `sql<TAB>` and I get

    $sql = "
        |
    ";

I start writing `SELECT *` and hit enter and the cursor end up in the beginning of the next line instead of at the same indent as the last line. What I would like is

    $sql = "
        SELECT *
        |
    ";

Am I alone in wanting this or am I missing some options that I can change to get what I want? :smiley:
