### ISSUE TITLE
nested switch statements gets indentation wrong

### ISSUE THREAD

**Issue by doits** [2072/PHP-Indenting-for-VIm#25]
This one gets the indentation confused:

```
<?
switch($one) {
case 'a':
    switch($two) {
    case 'b':
    }
    case 'c': # <-- should be one level higher
}
```

This should be:

```
<?
switch($one) {
case 'a':
    switch($two) {
    case 'b':
    }
case 'c':
}
```

**Comment by kevinc1984** [comment]
The official PHP site shows indentation at the "case" level:
```
switch ($i) {
    case 0:
        echo "i equals 0";
        break;
    case 1:
        echo "i equals 1";
        break;
    case 2:
        echo "i equals 2";
        break;
}
```
This plugin places `case` at the same level as `switch`. Any ideas why?

**Comment by 2072** [comment]
That's an option turned on by default.

I decided that indentation needed to convey some type of useful
information, I could not find a reason why 'case' were indented since they
have to be inside a switch block that cannot contain anything else anyway
so I decided to not indent them...

The option is described in php-indent help.

**Comment by kevinc1984** [comment]
Awesome! Thanks for the explanation, very helpful, and I totally agree!
