### ISSUE TITLE
Wrong indent on nested arrays

### ISSUE THREAD

**Issue by axelson** [2072/PHP-Indenting-for-VIm#41]
Currently has:

    public function indent()
    {
        return array(
            array('allow',  // allow all users to perform actions
            'actions'=>array('welcome','display'),
            'users'=>array('*'),
        ),
    )
    }

But should be:

    public function indent()
    {
        return array(
            array('allow',  // allow all users to perform actions
                'actions'=>array('welcome','display'),
                'users'=>array('*'),
            ),
        )
    }

Thanks for the indentation file! It's been quite useful otherwise.

**Comment by 2072** [comment]
This is a known limitation: if you want multi-line array definitions to look pretty, give them a good start by leaving the opening line empty, the following works:

```php
function indent()
{
     return array(
        array(
            'allow',  // allow all users to perform actions
            'actions'=>array('welcome','display'),
            'users'=>array('*'),
        ),
    );
}
```

The code above is easy to handle for the indentation script while handling a `(` or `[` that could be followed by anything is much more difficult...

In your example, the indent script only detect the `,` at the end of every lines and thinks it's the same list because the `(` that would indicate a new one is "obfuscated".
Implementing support for this kind of notation is not easy at all and would slow down the script as it would need to check  for `(` on every line and if it finds one, then it would need to make sure it's not actually inside a string/comment etc.. and then find the closing `)` and make sure it's not on the same line, etc....

This problem actually exists for all kind of block declarations:

```php
function indent()
{ $t = BLAH;
return BADINDENT;
}
```

As these are not standard notations for people who want properly indented code I chose not to implement support for them but to make sure that the indentation disturbances remain local as much as possible (any code after your array definition is correctly indented...).

**Comment by axelson** [comment]
Okay, that makes a lot of sense and is a great workaround. Thinking about it more putting the first entry on a separate line is much more clear and readable.
