### ISSUE TITLE
Read settings dynamically or later in an autocmd

### ISSUE THREAD

**Issue by davidosomething** [2072/PHP-Indenting-for-VIm#46]
If `g:PHP_outdentphpescape` is defined as zero AFTER the indent plugin is loaded, it is too late and the plugin will have already set the buffer local `b:PHP_outdentphpescape` to the default value (1)

occurs when loaded using a plugin manager (e.g. vim-plug)

**Comment by h3xx** [comment]
I assume you're invoking vim-plug in your .vimrc. Have you tried putting (**in this order**):

    let g:PHP_outdentphpescape = 0
    Plug '2072/PHP-Indenting-for-VIm'

**Comment by davidosomething** [comment]
Yup, it works like that, I'm asking if you can change it to read that variable later, like on BufEnter

**Comment by h3xx** [comment]
au BufReadPost *.php let b:PHP_outdentphpescape=0

**Comment by 2072** [comment]
Options are only applied once per buffer so that one can voluntarily uses different options for specific buffers. Re-applying global settings on each buffread would remove that feature.

You need to define global options before you first open/edit a PHP file into a new buffer. The indent script is executed/loaded each time the `FileType` auto command event is triggered but will leave early if it's already been executed for that buffer. (see the `LoadIndent()` function in the file `indent.vim` located in Vim's runtime path).
