### ISSUE TITLE
Why must syntax be on?

### ISSUE THREAD

**Issue by wayneashleyberry** [2072/PHP-Indenting-for-VIm#51]
What is the reason that PHP [requires syntax to be on](https://github.com/2072/PHP-Indenting-for-VIm/blob/bb850cf07fe25693c535cb39b276319818ab0208/indent/php.vim#L20) for indentation? Both JavaScript and Go indentation work fine when syntax is off.

Related: https://github.com/StanAngeloff/php.vim/issues/61

**Comment by 2072** [comment]
That's because the php's indent script uses some of the parsing done by the
syntax to detect what element it's dealing with.
For example without syntax it can't know if it's inside or outside php tags
(<?php... ?>), or if it's inside an heredoc or a multi-line string etc...

Compared to other indentation scripts this one tries to be very accurate
and fault tolerant (an indentation error will not spread to the whole file)
but this requires a more detailed parsing that only the syntax engine can
provide...
