### ISSUE TITLE
Indention problems in phtml files depending on semicolon in previous line

### ISSUE THREAD

**Issue by pjio** [2072/PHP-Indenting-for-VIm#68]
with semicolon behind the endif:
```
        <?php endif; ?>
<? # starts at col 1
```

without semicolon behind the endif:
```
        <?php endif ?>
        <? # keeps indention (expected!)
```

PHP_outdentphpescape is already set to 0

The behavior is triggered by creating a new line with 'o', 'O' or by typing '<?'

Another question: Which options should I use to keep the same indention for php and html tags?

**Comment by 2072** [comment]
It's because the indent script mistakes the `endif;` with an [heredoc closing identifier](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc).
I'll add an exception for the `end(if|switch|etc...)` identifiers but not that this [alternate syntax](http://php.net/manual/en/control-structures.alternative-syntax.php) is currently not supported and will exhibit strange behaviors!

About your 2nd question: there is no such option. PHP tags' position does not influence the indentation but are systematically moved to column 0 as PHP indentation is not influenced by the surrounding HTML which is completely ignored and left untouched...

Sorry for the very late reply, It seems a time compression space-time anomaly has formed around myself... Still trying to figure out how to dissipate this anomaly.
